name: Publish Newsletter
on:
  push:
    branches:
      - main
    paths:
      - "src/content/articles/**"
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Read Volta config
        id: volta
        run: |
          echo "NODE_VERSION=$(jq -r '.volta.node' package.json)" >> $GITHUB_OUTPUT
          echo "PNPM_VERSION=$(jq -r '.volta.pnpm' package.json)" >> $GITHUB_OUTPUT

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        with:
          version: ${{ steps.volta.outputs.PNPM_VERSION }}

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ steps.volta.outputs.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --strict-peer-dependencies --prefer-offline --verify-store-integrity

      - name: Publish to Buttondown
        run: pnpm run publish-to-buttondown
        env:
          BUTTONDOWN_API_KEY: ${{ secrets.BUTTONDOWN_API_KEY }}
          GIT_AUTHOR_NAME: "github-actions[bot]"
          GIT_COMMITTER_NAME: "github-actions[bot]"
          GIT_AUTHOR_EMAIL: "github-actions[bot]@users.noreply.github.com"
          GIT_COMMITTER_EMAIL: "github-actions[bot]@users.noreply.github.com"
          GIT_PUSH_URL: "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
